//! Embeds the authored content into the client binary.
//!
//! The client (native and web) always runs the exact content it was built
//! with — the same files CI validates — so a shipped build cannot drift
//! from its content. Tools and tests read from disk instead.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn walk(root: &Path, dir: &Path, entries: &mut Vec<(String, String)>) {
    for entry in fs::read_dir(dir).expect("content directory readable") {
        let entry = entry.expect("content entry readable");
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, entries);
        } else if path.extension().is_some_and(|ext| ext == "rhai") {
            let relative = path
                .strip_prefix(root)
                .expect("walked path under root")
                .to_string_lossy()
                .replace('\\', "/");
            let absolute = path
                .canonicalize()
                .expect("content path canonicalises")
                .to_string_lossy()
                .replace('\\', "/");
            println!("cargo:rerun-if-changed={absolute}");
            entries.push((relative, absolute));
        }
    }
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("manifest dir");
    let content_root = Path::new(&manifest).join("../../assets/content");
    println!("cargo:rerun-if-changed={}", content_root.display());

    let mut entries = Vec::new();
    walk(&content_root, &content_root, &mut entries);
    entries.sort();

    let mut code = String::from(
        "/// Embedded authored content, generated by build.rs.\n\
         pub static EMBEDDED_CONTENT: &[(&str, &str)] = &[\n",
    );
    for (relative, absolute) in entries {
        code.push_str(&format!(
            "    ({relative:?}, include_str!({absolute:?})),\n"
        ));
    }
    code.push_str("];\n");

    let out = PathBuf::from(env::var("OUT_DIR").expect("out dir")).join("embedded_content.rs");
    fs::write(out, code).expect("embedded content table writes");
}
